laravel/routes/web.php
<?php
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/browser', 'HomeController@browser')->name('browser');
Route::get('/fb', 'HomeController@fb')->name('fb');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/blogs', 'HomeController@blogs')->name('blogs');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/faqs', 'HomeController@faqs')->name('faqs');
Route::get('/services', 'HomeController@services')->name('services');
Route::get('/check-scrap', 'HomeController@checkScrap');
Route::get('/check-logout', 'HomeController@checkLogout');
Route::get('/check-date', 'HomeController@checkDate');
Route::get('/check-pdf-event', 'HomeController@checkPdfEvent');

Route::get('/past-performances', 'HomeController@pastPerformances')->name('past-performances');
Route::get('/services', 'HomeController@services')->name('services');
Route::get('/testimonials', 'HomeController@testimonials')->name('testimonials');
Route::get('/risk-profile', 'HomeController@riskProfile')->name('risk-profile');
Route::get('/terms', 'HomeController@terms')->name('terms');
Route::get('/privacy', 'HomeController@privacy')->name('privacy');
Route::get('login/facebook', 'HomeController@redirectToProvider');
Route::get('login/facebook/callback', 'HomeController@handleProviderCallback');
Route::get('ip', 'UserController@checkIpDetail');
Route::get('stock', 'UserController@checkStock');
Route::get('api-call', function(){
	return AlphaVantage\Api::stock()->daily('NSE:KEC');
});

Route::group(['middleware' => 'paid'], function() {
    Route::get('/current-recommendation', 'HomeController@currentRecommendation')->name('current-recommendation');
    Route::get('/investors-forum', 'HomeController@investorForum')->name('investor');
	Route::get('/reports/{id}/{name}', 'HomeController@stockReports')->name('stock-reports');
	Route::get('/view-report/{id}/{name}', 'StockReportController@viewReport')->name('view-report');
    Route::get('/download-report/{id}/{name}', 'StockReportController@downloadReport')->name('download-report');
});
Route::get('/admin/login', function() {
	return view('admin.login');
});

Route::resource('enquiry', 'EnquiryController');
Route::resource('investor-forum', 'InvestorForumController');
Route::get('pdf', 'UserController@pdf');
Route::get('watermark', 'UserController@watermark');

Route::get('client/{id}/kyc', 'KycController@upload')->name('kyc-upload');
Route::get('client/{id}/risk-profile/{edit?}', 'RiskProfileController@upload')->name('risk-upload');
Route::get('client/{id}/risk-profile-result', 'RiskProfileController@result')->name('risk-result');
Route::get('check', 'UserController@checkPDF');
Route::resource('forum-answer', 'ForumAnswerController');

Route::get('/pay','PaymentController@getPay')->name('get-pay');

Route::post('/paydemo','PaymentController@getPay')->name('pay');

Route::post('/placeorder','PaymentController@getPay')->name('placeorder');

Route::post('/paystatus','PaymentController@orderStatus')->name('orderStatus');

Route::resource('payment', 'PaymentController');

Route::get('/booked/order/{id}/{status?}', 'PaymentController@previous')->name('previous');

Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function(){	
	Route::get('/', function() {
		return view('admin.dashboard');
	})->name('home');
	
	Route::get('/check', function() {
		return view('admin.emails.normal');
	});

	Route::get('/download-kyc', 'UserController@downloadKyc')->name('download-kyc');
	Route::get('/download-stock', 'StockController@getStock')->name('download-stock');

	Route::resource('kyc', 'KycController');
	Route::resource('faq', 'FaqController');
	Route::resource('risk-profile', 'RiskProfileController');
	Route::resource('user', 'UserController');
	
	Route::get('clients/{type}/{tname}', 'UserController@getClients')->name('clients');
	
	Route::get('risk-profiles/{id}', 'RiskProfileController@allRiskProfile')->name('risk-profiles');
	Route::get('kycs/{id}/{type?}', 'KycController@allKycs')->name('kycs');
	Route::get('kycs-new', 'KycController@allKycsNew')->name('kycs-new');
	Route::get('all-user', 'UserController@allUser')->name('all-user');
	Route::get('all-stocks', 'StockController@allStocks')->name('all-stocks');	
	Route::get('all-logs', 'LoginLogController@allLogs')->name('all-logs');
	Route::get('all-logs-users', 'LoginLogController@allLogsUsers')->name('all-logs-users');
	Route::get('logs-users', 'LoginLogController@viewLogUser')->name('logs-users');	
	Route::get('all-forums', 'InvestorForumController@allForums')->name('all-forums');
	Route::get('logs/{id}', 'LoginLogController@logs')->name('logs');
	Route::post('payment-form', 'UserController@paymentForm')->name('payment-form');
	Route::post('block-form', 'LoginLogController@blockForm')->name('block-form');    
	Route::post('answer-form', 'InvestorForumController@answerForm')->name('answer-form');
	Route::post('approve-form', 'StockController@approveForm')->name('approve-form');	
	Route::post('all-answers', 'ForumAnswerController@allAnswers')->name('all-answers');

	Route::resource('investor-forum', 'InvestorForumController');
	Route::resource('current-recommendation', 'CurrentRecommendationController');
	Route::resource('stock', 'StockController');
	Route::resource('login-log', 'LoginLogController');
	Route::resource('stock-report', 'StockReportController');
	Route::resource('forum-answer', 'ForumAnswerController');
});

laravel/resources/views/admin/forms/all_answers.blade.php
<div class="form-group">
    <table id="forum-table" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Answer</th>
                <th>User</th>
                <th>Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($if->answers()->get() as $ans)
            <tr>
                <td>{{ $ans->fa_answer }}</td>
                <td>{{ $ans->user->name }}</td>
                <td>{{ $ans->fa_created_at->format('jS M, Y - h:i A') }}</td>
                <td>
                    <form action="{{ route('admin.forum-answer.update', ['id' => $ans->fa_id]) }}" method="post">
                        <input type="hidden" name="_method" value="PUT">
                        <input type="hidden" name="approve" value="{{ $ans->fa_approve ? 0 : 1 }}">
                        {{ csrf_field() }}
                        @if ($ans->fa_approve)
                            <button class="btn btn-sm btn-danger">Deny</button>
                        @else
                            <button class="btn btn-sm btn-success">Approve</button>
                        @endif
                    </form>
                </td>
            </tr>
            @empty

            @endforelse
        </tbody>
    </table>
</div>

laravel/resources/views/admin/forms/answer_form.blade.php
<div class="form-group">
    <form id = "answerForm">
        <input type="hidden" name="user" value="{{ Auth::id() }}">
        <input type="hidden" name="question" value="{{ $qus->if_id }}">
        <input type="hidden" name="admin" value="1">        
        <div class="form-group">
            <textarea class="form-control" placeholder="Answer" rows="5" readonly>{{ $qus->if_question }}</textarea>
        </div>        
        <div class="form-group">
            <textarea class="form-control" placeholder="Answer" rows="5" name = "answer"></textarea>
        </div>
        <div class="form-group">
            <button class="btn btn-success">Answer</button>            
        </div>
    </form>
</div>

<script type="text/javascript">
    addAnswer();
</script>

laravel/resources/views/admin/forms/article_form.blade.php
@push('header')
@php
$ID = 'article';
@endphp
<script>
	ID = '{{ $ID }}';
</script>

<style type="text/css">
#imagePreview{
	height: 150px;
	object-fit: contain;
}
</style>
@endpush

<form id = "{{ $ID }}Form" class="form-horizontal form-label-left" enctype="multipart/formdata">	
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Title
		</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input type="text" class="form-control col-md-7 col-xs-12" name = "title" value="{{ $article->ar_title or '' }}">
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Display Image
		</label>
		<div class="col-md-3 col-sm-3 col-xs-12 text-center">			
			<div class="clearfix"></div>
			<img src="{{ asset(isset($article) ? $article->ar_image : 'images/no-image.png') }}" id = "imagePreview">
			<div class="clearfix"></div>
			<input type = "file" id ="image" accept="image/png, image/jpeg, image/jpg" class="hidden form-control1" name = "image">		
			<label class="btn btn-success" for = "image">Choose Image</label>			
		</div>
	</div>
	<div class="form-group label-floating">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">PDF/DOCX/DOC</label>
		<input type = "file" id ="pdf" accept="application/msword, text/plain, application/pdf" class="hidden form-control1" name="pdf">
		<label class="btn btn-success" for = "pdf">Choose PDF/DOCX/DOC</label>
	</div> 
	@isset ($article)
	<input type="hidden" name="id" value = "{{ $article->ar_id }}">
	@endisset
	<div class="ln_solid">
	</div>
	<div class="form-group text-center">							
		<button type="submit" class="btn btn-success">{{ isset($article) ? 'Update' : 'Add' }}</button>
	</div>					
</form>
@push('footer')
<script>
	imageUpload('image');		
	$('#{{ $ID }}Form').CRUD({
		url : '{{ route('admin.'.$ID.'.store') }}'
	});
</script>
@endpush

laravel/resources/views/admin/forms/block_form.blade.php
<div class="form-group">
	<form action="{{ route('admin.user.update',['id' => $user->id]) }}" method="post">
		{{ csrf_field() }}
		<input type="hidden" name="_method" value = "PUT">
		<input type="hidden" name="block" value = "{{ $user->block ? 0 : 1 }}">
		<div class="form-group">
			<textarea class="form-control" placeholder="Send some notes" rows="5" name = "note"></textarea>
		</div>
		<div class="form-group">			
			<button class="btn btn-success">{{ $user->block ? 'Un-Block' : 'Block' }} Access</button>
		</div>
	</form>
</div>

laravel/resources/views/admin/forms/delete_form.blade.php
<form id = "deleteForm" method = "post">
	{{ csrf_field() }}
	<input type="hidden" name="id" value = "">
	<input type="hidden" name="_method" value = "DELETE">
	<button type = "submit" class="btn btn-danger">Yes</button>
	<button type = "button" class="btn btn-success" data-dismiss="modal">No</button>
</form>

laravel/resources/views/admin/forms/faq_form.blade.php
@push('header')
<link href="{{ asset('css/quill.snow.css') }}" rel="stylesheet" />
@endpush

<form id = "{{ $ID }}Form" class="form-horizontal form-label-left" enctype="multipart/formdata">	
	<div class="form-group">
		<label class="control-label col-md-3 col-sm-3 col-xs-12">Question</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<div id = "qus">{!! $faq->faq_qus or '' !!}</div>
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-md-3 col-sm-3 col-xs-12">Answer</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<div id = "ans">{!! $faq->faq_ans or '' !!}</div>
		</div>
	</div>
	@isset ($faq)
	<input type="hidden" name="id" value = "{{ $faq->faq_id }}">
	@endisset
	<div class="ln_solid">
	</div>
	<div class="form-group text-center">							
		<button type="submit" class="btn btn-success">{{ isset($faq) ? 'Update' : 'Add' }}</button>
	</div>					
</form>
@push('footer')
<script src="{{ asset('js/quill.min.js') }}"></script>
<script>
	var qus = new Quill('#qus', {      
		placeholder: 'Question...',    
		theme: 'snow'
	});

	var ans = new Quill('#ans', {
		placeholder: 'Answer...',    
		theme: 'snow'
	});
	$('#{{ $ID }}Form').CRUD({
		url : '{{ route('admin.'.$ID.'.store') }}',
		extraVariables : function(){
			return {
				'qus' : document.querySelector("#qus .ql-editor").innerHTML,
				'ans' : document.querySelector("#ans .ql-editor").innerHTML
			};
		}
	});
</script>
@endpush

laravel/resources/views/admin/forms/investor_education_form.blade.php
@push('header')
@php
$ID = 'investor-education';
@endphp
<script>
	ID = '{{ $ID }}';
</script>

<style type="text/css">
#imagePreview{
	height: 150px;
	object-fit: contain;
}
</style>
@endpush

<form id = "{{ $ID }}Form" class="form-horizontal form-label-left" enctype="multipart/formdata">	
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Title
		</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input type="text" class="form-control col-md-7 col-xs-12" name = "title" value="{{ $investorEducation->ie_title or '' }}">
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Display Image
		</label>
		<div class="col-md-3 col-sm-3 col-xs-12 text-center">			
			<div class="clearfix"></div>
			<img src="{{ asset(isset($investorEducation) ? $investorEducation->ie_image : 'images/no-image.png') }}" id = "imagePreview">
			<div class="clearfix"></div>
			<input type = "file" id ="image" accept="image/png, image/jpeg, image/jpg" class="hidden form-control1" name = "image">		
			<label class="btn btn-success" for = "image">Choose Image</label>			
		</div>
	</div>	
	@isset ($investorEducation)
	<input type="hidden" name="id" value = "{{ $investorEducation->ie_id }}">
	@endisset
	<div class="ln_solid">
	</div>
	<div class="form-group text-center">							
		<button type="submit" class="btn btn-success">{{ isset($investorEducation) ? 'Update' : 'Add' }}</button>
	</div>					
</form>
@push('footer')
<script>	
	imageUpload('image');
	$('#{{ $ID }}Form').CRUD({
		url : '{{ route('admin.'.$ID.'.store') }}'
	});
</script>
@endpush

laravel/resources/views/admin/forms/monthly_performance_form.blade.php
@push('header')
@php
$ID = 'monthly-performance';
@endphp
<script>
	ID = '{{ $ID }}';
</script>
@endpush

<form id = "{{ $ID }}Form" class="form-horizontal form-label-left" enctype="multipart/formdata">
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Date
		</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input  type="date" class="form-control col-md-7 col-xs-12" name = "date" value="{{ $mp->mp_date or '' }}">
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Quants Alpha
		</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input step=".01" type="number" class="form-control col-md-7 col-xs-12" name = "dns" value="{{ $mp->mp_dns or '' }}">
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">INDEX
		</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input type="number" step=".01" class="form-control col-md-7 col-xs-12" name = "nifty" value="{{ $mp->mp_nifty or '' }}">
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">INDEX + Quants Alpha
		</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input step=".01" type="number" class="form-control col-md-7 col-xs-12" name = "nifty_dns" value="{{ $mp->mp_nifty_dns or '' }}">
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">FD
		</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input step=".01" type="number" class="form-control col-md-7 col-xs-12" name = "fd" value="{{ $mp->mp_fd or '' }}">
		</div>
	</div>
	<div class="form-group">
		<label step=".01" class="control-label col-md-4 col-sm-4 col-xs-12">FD + Quants Alpha
		</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input step=".01" type="number" class="form-control col-md-7 col-xs-12" name = "fd_dns" value="{{ $mp->mp_fd_dns or '' }}">
		</div>
	</div>
	@isset ($mp)
	    <input type="hidden" name="id" value = "{{ $mp->mp_id }}">
	@endisset
	<div class="ln_solid">
	</div>
	<div class="form-group text-center">							
		<button type="submit" class="btn btn-success">{{ isset($mp) ? 'Update' : 'Add' }}</button>
	</div>					
</form>
@push('footer')
<script>		
	$('#{{ $ID }}Form').CRUD({
		url : '{{ route('admin.'.$ID.'.store') }}'
	});
</script>
@endpush

laravel/resources/views/admin/forms/payment_form.blade.php
<div class="form-group">
	<form action="{{ route('admin.user.update',['id' => $user->id]) }}" method="post">
		{{ csrf_field() }}
		<input type="hidden" name="_method" value = "PUT">
		<input type="hidden" name="paid" value="{{ $user->paid ? 0 : 1 }}">
		@php
		if($user->lastSubscriptionLog()->count()) {
			$sl = $user->lastSubscriptionLog->first()->subscription;
		}
		@endphp
		@isset ($sl)		    
			<input type="hidden" name="subscription" value="{{ $sl->sub_id }}">
		@endisset
		<div class="form-group">
			<input type="number" name="amount" class="form-control" placeholder="Enter amount recieved" value = "{{ $sl->sub_amount or 25000 }}">
		</div>
		<div class="form-group">
			<label class="pull-left">Year of Subscription</label>
			<select class="form-control" name="year">
				<option value = "1" {{ isset($sl) ? ($sl->sub_year == '1' ? 'selected' : '') : '' }}>1 Year</option>
				<option value = "2" {{ isset($sl) ? ($sl->sub_year == '2' ? 'selected' : '') : '' }}>2 Year</option>
			</select>			
		</div>
		<div class="form-group">
			<textarea class="form-control" placeholder="Send some notes" rows="5" name = "note"></textarea>
		</div>
		<div class="form-group">
			@if ($user->paid)
			<button class="btn btn-danger">Cancel Subscription</button>
			@else
				@if($user->lastSubscriptionLog()->count())
					<button class="btn btn-success">Continue Subscription</button>
				@else
					<button class="btn btn-success">Approve Subscription</button>
				@endif
			@endif
		</div>
	</form>
</div>

laravel/resources/views/admin/forms/stock_form.blade.php
<form id = "{{ $ID }}Form" class="form-horizontal form-label-left" enctype="multipart/formdata">	
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Title</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input type="text" class="form-control" name = "title" value="{{ $stock->st_title or '' }}">
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Symbol</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input type="text" class="form-control" name = "symbol" value="{{ $stock->st_symbol or '' }}">
		</div>
	</div>
	@isset ($stock)
	<input type="hidden" name="id" value = "{{ $stock->st_id }}">
	@endisset
	<div class="ln_solid">
	</div>
	<div class="form-group text-center">							
		<button type="submit" class="btn btn-success">{{ isset($stock) ? 'Update' : 'Add' }}</button>
	</div>					
</form>
@push('footer')
<script>
	$('#{{ $ID }}Form').CRUD({
		url : '{{ route('admin.'.$ID.'.store') }}'
	});
</script>
@endpush

laravel/resources/views/admin/forms/stock_report_form.blade.php
@push('header')
<link href="{{ asset('css/select2.css') }}" rel="stylesheet" />
@endpush

<form id = "{{ $ID }}Form" class="form-horizontal form-label-left" enctype="multipart/formdata">	
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Stock</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<select class="form-control stock" name = "stock">
				<option value="-1">--select--</option>
				@forelse (\App\Stock::where(['st_active' => 1])->get() as $st)
				<option value="{{ $st->st_id }}">{{ $st->st_symbol }}</option>
				@empty
				@endforelse
			</select>
		</div>
	</div>	
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Title</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input type="text" class="form-control" name = "title">
		</div>
	</div>	
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Upload Report (PDF)</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input type="file" class="form-control" name = "pdf">
		</div>
	</div>	
	<div class="ln_solid">
	</div>
	<div class="form-group text-center">							
		<button type="submit" class="btn btn-success">{{ isset($cr) ? 'Update' : 'Add' }}</button>
	</div>					
</form>
@push('footer')
<script src="{{ asset('js/select2.min.js') }}"></script>
<script>
	$('.stock').select2();
	$('#{{ $ID }}Form').CRUD({
		url : '{{ route('admin.'.$ID.'.store') }}'
	});
</script>
@endpush

laravel/resources/views/admin/forms/user_form.blade.php
@push('header')
@php
$ID = 'client';
@endphp
<script>
	ID = '{{ $ID }}';
</script>
@endpush

<form id = "{{ $ID }}Form" class="form-horizontal form-label-left" enctype="multipart/formdata">	
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Client ID
		</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input type="text" class="form-control col-md-7 col-xs-12" name = "ud[client_id]" value="{{ $user->detail->ud_client_id or '' }}">
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Name
		</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input type="text" class="form-control col-md-7 col-xs-12" name = "name" value="{{ $user->name or '' }}">
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Mobile
		</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input type="number" min = "7000000000" max = "9999999999" class="form-control col-md-7 col-xs-12" name = "ud[mobile]" value="{{ $user->detail->ud_mobile or '' }}">
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Alternate Mobile
		</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input type="number" min = "7000000000" max = "9999999999" class="form-control col-md-7 col-xs-12" name = "ud[alt_mobile]" value="{{ $user->detail->ud_alt_mobile or '' }}">
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Email
		</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input type="email" class="form-control col-md-7 col-xs-12" name = "email" value="{{ $user->email or '' }}">
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Portfolio Size
		</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input type="number" min = "0" max = "9999999999" class="form-control col-md-7 col-xs-12" name = "ud[portfolio_size]" value="{{ $user->detail->ud_portfolio_size or '' }}">
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Address
		</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<textarea class="form-control col-md-7 col-xs-12" name = "ud[address]">{{ $user->detail->ud_address or '' }}</textarea>
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-md-4 col-sm-4 col-xs-12">Date Inception
		</label>
		<div class="col-md-6 col-sm-6 col-xs-12">
			<input type="date" class="form-control col-md-7 col-xs-12" name = "ud[date_inception]" value="{{ $user->detail->ud_date_inception or '' }}">
		</div>
	</div>	
	@isset ($user)
	    <input type="hidden" name="sid" value = "{{ $user->id }}">
	@endisset
	<div class="ln_solid">
	</div>
	<div class="form-group text-center">							
		<button type="submit" class="btn btn-success">{{ isset($user) ? 'Update' : 'Add' }}</button>
	</div>					
</form>
@push('footer')
<script>		
	$('#{{ $ID }}Form').CRUD({
		url : '{{ route('admin.user.update') }}',
		processResponse: function(data){
			if(data.msg == 'successU'){
				location.reload();
			}			
		}
	});
</script>
@endpush

laravel/resources/views/admin/forms/view_kyc.blade.php
<form id = "rejectForm" action="{{ route('admin.kyc.update',['id' => $kyc->kyc_id]) }}" method="post">
	<div class="text-center">
		<div class="form-group">
			<label>PAN Number: {{ $kyc->kyc_number }}</label>
		</div>
		<div class="form-group">	
			<a href="{{ asset($kyc->kyc_image) }}" download><img src="{{ asset($kyc->kyc_image) }}" style="max-width: 500px"></a>
		</div>
		@if (!$kyc->kyc_reject)
		<div class="form-group">
			{{ csrf_field() }}
			<input type="hidden" name="_method" value = "PUT">
			<input type="hidden" name="status" value="{{ $kyc->kyc_status ? 0 : 1 }}">		
			<button class="btn btn-success" name = "approve" value="approve">Approve It</button>		
			<button type = "button" class="btn btn-danger" id = "rejectBtn">Reject</button>			
		</div>
		@endif
	</div>
	<div id = "reasonBox" class="hidden form-group">
		<fieldset>			
			<legend>Reasons</legend>
			@forelse (\App\RejectReason::where(['rr_default' => 1])->get() as $rr)
			<div class="form-group">
				<input type="checkbox" name="reason[]" value="{{ $rr->rr_id }}" id = "{{ $rr->rr_id }}"> <label for = "{{ $rr->rr_id }}">{{ $rr->rr_title }}</label>
			</div>
			@empty				
			@endforelse
			<div class="form-group">
				<input type="checkbox" id = "other"> <label for = "other">Other</label>
			</div>
			<div class="form-group">
				<textarea name="new_reason" id = "otherBox" placeholder="Personalise reason" class="hidden form-control" rows="3"></textarea>
			</div>
			<div class="form-group">
				<button class="btn btn-danger" name = "reject" value="reject">Submit</button>
			</div>
		</fieldset>
	</div>
</form>

<script type="text/javascript">
	others();
</script>

laravel/resources/views/admin/forms/view_risk_profile_details.blade.php
<form>
	@forelse ($risk_questions as $k => $rq)
	<div class="form-group">
		<label>{{ ($k+1).'. '.$rq->rq_qus }}</label>
		@if ($k)
		@forelse ($rq->options()->get() as $ro)
		@php
		$chk = $riskAns[$k] ? ($riskAns[$k]->rpa_ans == $ro->ro_id ? 'checked' : '') : '';
		@endphp
		<div>
			<input type="radio" id = "op{{ $ro->ro_id }}" name="op{{ $rq->rq_id }}" value="{{ $ro->ro_id }}" {{ $chk }} disabled>
			<label for="op{{ $ro->ro_id }}">{{ $ro->ro_option }}</label>
		</div>							
		@empty							
		@endforelse
		@else
		<div style="width: 30%;" class="input-group date" >
			<input type="date" value = "{{ $rp->rp_dob }}" class="form-control" readonly>
		</div>						
		@endif
	</div>
	@empty

	@endforelse
</form>