laravel/routes/web.php
<?php
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/browser', 'HomeController@browser')->name('browser');
Route::get('/fb', 'HomeController@fb')->name('fb');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/blogs', 'HomeController@blogs')->name('blogs');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/faqs', 'HomeController@faqs')->name('faqs');
Route::get('/services', 'HomeController@services')->name('services');
Route::get('/check-scrap', 'HomeController@checkScrap');
Route::get('/check-logout', 'HomeController@checkLogout');
Route::get('/check-date', 'HomeController@checkDate');
Route::get('/check-pdf-event', 'HomeController@checkPdfEvent');

Route::get('/past-performances', 'HomeController@pastPerformances')->name('past-performances');
Route::get('/services', 'HomeController@services')->name('services');
Route::get('/testimonials', 'HomeController@testimonials')->name('testimonials');
Route::get('/risk-profile', 'HomeController@riskProfile')->name('risk-profile');
Route::get('/terms', 'HomeController@terms')->name('terms');
Route::get('/privacy', 'HomeController@privacy')->name('privacy');
Route::get('login/facebook', 'HomeController@redirectToProvider');
Route::get('login/facebook/callback', 'HomeController@handleProviderCallback');
Route::get('ip', 'UserController@checkIpDetail');
Route::get('stock', 'UserController@checkStock');
Route::get('api-call', function(){
	return AlphaVantage\Api::stock()->daily('NSE:KEC');
});

Route::group(['middleware' => 'paid'], function() {
    Route::get('/current-recommendation', 'HomeController@currentRecommendation')->name('current-recommendation');
    Route::get('/investors-forum', 'HomeController@investorForum')->name('investor');
	Route::get('/reports/{id}/{name}', 'HomeController@stockReports')->name('stock-reports');
	Route::get('/view-report/{id}/{name}', 'StockReportController@viewReport')->name('view-report');
    Route::get('/download-report/{id}/{name}', 'StockReportController@downloadReport')->name('download-report');
});
Route::get('/admin/login', function() {
	return view('admin.login');
});

Route::resource('enquiry', 'EnquiryController');
Route::resource('investor-forum', 'InvestorForumController');
Route::get('pdf', 'UserController@pdf');
Route::get('watermark', 'UserController@watermark');

Route::get('client/{id}/kyc', 'KycController@upload')->name('kyc-upload');
Route::get('client/{id}/risk-profile/{edit?}', 'RiskProfileController@upload')->name('risk-upload');
Route::get('client/{id}/risk-profile-result', 'RiskProfileController@result')->name('risk-result');
Route::get('check', 'UserController@checkPDF');
Route::resource('forum-answer', 'ForumAnswerController');

Route::get('/pay','PaymentController@getPay')->name('get-pay');

Route::post('/paydemo','PaymentController@getPay')->name('pay');

Route::post('/placeorder','PaymentController@getPay')->name('placeorder');

Route::post('/paystatus','PaymentController@orderStatus')->name('orderStatus');

Route::resource('payment', 'PaymentController');

Route::get('/booked/order/{id}/{status?}', 'PaymentController@previous')->name('previous');

Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function(){	
	Route::get('/', function() {
		return view('admin.dashboard');
	})->name('home');
	
	Route::get('/check', function() {
		return view('admin.emails.normal');
	});

	Route::get('/download-kyc', 'UserController@downloadKyc')->name('download-kyc');
	Route::get('/download-stock', 'StockController@getStock')->name('download-stock');

	Route::resource('kyc', 'KycController');
	Route::resource('faq', 'FaqController');
	Route::resource('risk-profile', 'RiskProfileController');
	Route::resource('user', 'UserController');
	
	Route::get('clients/{type}/{tname}', 'UserController@getClients')->name('clients');
	
	Route::get('risk-profiles/{id}', 'RiskProfileController@allRiskProfile')->name('risk-profiles');
	Route::get('kycs/{id}/{type?}', 'KycController@allKycs')->name('kycs');
	Route::get('kycs-new', 'KycController@allKycsNew')->name('kycs-new');
	Route::get('all-user', 'UserController@allUser')->name('all-user');
	Route::get('all-stocks', 'StockController@allStocks')->name('all-stocks');	
	Route::get('all-logs', 'LoginLogController@allLogs')->name('all-logs');
	Route::get('all-logs-users', 'LoginLogController@allLogsUsers')->name('all-logs-users');
	Route::get('logs-users', 'LoginLogController@viewLogUser')->name('logs-users');	
	Route::get('all-forums', 'InvestorForumController@allForums')->name('all-forums');
	Route::get('logs/{id}', 'LoginLogController@logs')->name('logs');
	Route::post('payment-form', 'UserController@paymentForm')->name('payment-form');
	Route::post('block-form', 'LoginLogController@blockForm')->name('block-form');    
	Route::post('answer-form', 'InvestorForumController@answerForm')->name('answer-form');
	Route::post('approve-form', 'StockController@approveForm')->name('approve-form');	
	Route::post('all-answers', 'ForumAnswerController@allAnswers')->name('all-answers');

	Route::resource('investor-forum', 'InvestorForumController');
	Route::resource('current-recommendation', 'CurrentRecommendationController');
	Route::resource('stock', 'StockController');
	Route::resource('login-log', 'LoginLogController');
	Route::resource('stock-report', 'StockReportController');
	Route::resource('forum-answer', 'ForumAnswerController');
});

laravel/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'type', 'soft_delete', 'kyc', 'mobile', 'risk', 'paid', 'block'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    
    public function subscriptions() {
        return $this->hasMany(\App\Subscription::class, 'sub_user');
    }
    
    public function latestSubscription() {
        return $this->hasMany(\App\Subscription::class, 'sub_user')->orderBy('sub_created_at', 'desc');
    }

    public function lastSubscriptionLog() {
        return $this->hasMany(\App\SubscriptionLog::class, 'sl_user')->orderBy('sl_created_at', 'desc');
    }

    public function kycDetail(){
        return $this->hasMany(\App\Kyc::class, 'kyc_user');
    }

    public function riskProfile() {
        return $this->hasMany(\App\RiskProfile::class, 'rp_user');
    }
            
    public function recentRiskProfile() {
        return $this->hasOne(\App\RiskProfile::class, 'rp_user')->orderBy('rp_created_at', 'desc');
    }

    public function loginLogs() {
        return $this->hasMany(\App\LoginLog::class, 'll_user');
    }
}

laravel/app/Http/Controllers/UserController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Database\QueryException;
use App\Http\Traits\GetData;
use App\User;
use App\Kyc;
use App\SubscriptionLog;
use \Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use App\Subscription;
use Yajra\Datatables\Datatables;
use App\Events\EmailEvent;
use DB;
use setasign\Fpdi;
use App\Pdf\PDF;
use Intervention\Image\ImageManager;
// use Intervention\Image;

class UserController extends Controller
{
    use GetData;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */    
    public function downloadKyc(){

    // $files = Kyc::where('kyc_status', 0)->get()->pluck('kyc_image')->toArray();
        $files = Kyc::get()->pluck('kyc_image')->toArray();

    // $rmfiles = Kyc::select(DB::raw("REPLACE(kyc_image,'img/pan-cards/', '') as kyc_image"))->where('kyc_status', 1)->get()->pluck('kyc_image')->toArray();

        \Zipper::make('aurum-new-kyc-documents.zip')->add($files)->close();

        return response()->download('aurum-new-kyc-documents.zip');
    }    

    public function allUser(Request $r){        
        $users = User::where([
            'soft_delete' => 0,
            'type' => 102,
            'paid' => $r->type
        ])->orderBy('created_at', 'desc');

        return Datatables::of($users)->editColumn('created_at', function ($user) {
            return $user->created_at->format('jS M, Y - h:i A');
        })->addColumn('color', function ($user) {
            $newKyc = $user->kycDetail()->orderBy('kyc_created_at', 'desc')->first();
            if($newKyc) {
                if ($newKyc->kyc_status) {
                    return 'tr-green';
                }else {
                    return 'tr-yellow';
                }
            }else{
                return 'tr-red';                
            }
        })->addColumn('action', function ($user) {
            if($user->paid){
                $first = '<button class="btn btn-danger btn-sm" onclick="viewDetail('.$user->id.');"><i class="fa fa-times"></i> Cancel</button>';
            }else{
                if($user->lastSubscriptionLog()->count()) {
                    $first = '<button class="btn btn-warning btn-sm" onclick="viewDetail('.$user->id.');"><i class="fa fa-play"></i> Continue</button>';
                }else{
                    $first = '<button class="btn btn-success btn-sm" onclick="viewDetail('.$user->id.');"><i class="fa fa-check"></i> Approve</button>';                
                }
            }
            return '<a class="btn btn-success btn-sm" href = "'.route('admin.risk-profiles',['id' => $user->id]).'"><i class="fa fa-eye"></i> Risk Profiles ('.$user->riskProfile()->count().')</a>| <a class="btn btn-success btn-sm" href = "'.route('admin.kycs',['id' => $user->id]).'"><i class="fa fa-eye"></i> Kycs ('.$user->kycDetail()->count().')</a>| '.$first;
        })
        ->make(true);        
    }

    public function index() {
        // return view('admin.view_users')->with(['users' => $this->allUser()]);
    }

    public function getClients($type, $tname) {
        return view('admin.view_users')->with(['type' => $type, 'tname' => $tname]);
    }

    public function paymentForm(Request $r){
        return view('admin.forms.payment_form')->with(['user' => User::find($r->id)]);
    }

    public function create(){

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $r, $id)
    {
        $user = User::find($id);
        $emailSet['to'] = ['email' => $user->email,'name' => $user->name];
        $emailSet['blade'] = 'normal';

        if(isset($r->block)){
            $user->update(['block' => $r->block]);
            if($r->block){                
                $emailSet['data'] = [
                    'note' => $r->note,
                    'msg' => __('email.block')
                ];
                $emailSet['subject'] = __('email.block_subject');
            }else{
                $emailSet['data'] = [
                    'note' => $r->note,
                    'msg' => __('email.unblock')
                ];
                $emailSet['subject'] = __('email.unblock_subject');
            }
            event(new EmailEvent($emailSet));
            return redirect()->back();
        }
        if(isset($r->paid)){
            if(isset($r->subscription)) {
                $sub = Subscription::find($r->subscription);

                if($sub->sub_cancel){
                    $emailSet['data'] = [
                        'note' => $r->note,
                        'msg' => __('email.resume_subscription', ['amount' => number_format($sub->sub_amount)])
                    ];
                    $emailSet['subject'] = __('email.resume_subject');

                }else{
                    $emailSet['data'] = [
                        'note' => $r->note,
                        'msg' => __('email.cancel_subscription')
                    ];                    
                    $emailSet['subject'] = __('email.cancel_subscription_subject');                    
                }                
                $sub->update(['sub_cancel' => !$sub->sub_cancel]);                    
            }else{
                $sub = Subscription::create([
                    'sub_user' => $id,
                    'sub_amount' => $r->amount, 
                    'sub_note' => $r->note, 
                    'sub_updated_by' => Auth::id(),
                    'sub_year' => $r->year,
                    'sub_end_data' => Carbon::now()->addYear($r->year)
                ]);
                
                $emailSet['data'] = [
                    'note' => $r->note,
                    'msg' => __('email.confirmation_success', ['amount' => number_format($sub->sub_amount)]), 
                    'route' => route('kyc-upload',['id' => $id])
                ];
                
                $emailSet['subject'] = __('email.confirmation_subject');
                
                
            }
            
            SubscriptionLog::create([
                'sl_user' => $user->id,
                'sl_added_by' => Auth::id(),
                'sl_status' => $r->paid,
                'sl_sub' => $sub->sub_id 
            ]);        

            event(new EmailEvent($emailSet));
            
            $user->update(['paid' => $r->paid]);
            
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id){        
    }    

    public function checkIpDetail()
    {
        return $this->ipDetails($this->checkIp());
    }

    // public function checkStock() {
    //     return $this->stock();
    // }
}

laravel/resources/views/users/blogs.blade.php
@extends('users.layouts.master')

@section('content')
<!-- section1 -->
<section class="blog-sec1"> 
	<div class="container">				
		<div class="row">

			<div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
				<div class="blog-all">
					<h1>All Blogs</h1>
					<hr>
					<ul class="nav nav-tabs nav-stacked">
						<li class="active"><a data-toggle="tab" href="#home">2018</a></li>
						<li><a data-toggle="tab" href="#menu1">2017</a></li>
						<li><a data-toggle="tab" href="#menu2">2016</a></li>
					</ul>								
				</div>
			</div>	

			<div class="col-lg-9 col-md-9 col-sm-8 col-xs-12">

				<div class="tab-content">
					<div id="home" class="tab-pane fade in active">
						<div class="blog-sec1-mid">
							<div class="row">								
								<div class="blog-sec1-text">
									<h1>Article Name</h1>
									<ul>
										<li class="blog-li1"><span>By:</span> Author Name</li>
										<li class="blog-li3">Comment</li>
										<li class="blog-li2"><span>Posted on:</span> 14<sup>th</sup> April 2018</li>
										<li class="blog-li4">Like</li>	
									</ul>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
									<a href="#" class="blog-btn">Read More</a>
								</div>
							</div>								
						</div>

						<div class="blog-sec1-mid">
							<div class="row">									
								<div class="blog-sec1-text">
									<h1>Article Name</h1>
									<ul>
										<li class="blog-li1"><span>By:</span> Author Name</li>
										<li class="blog-li3">Comment</li>
										<li class="blog-li2"><span>Posted on:</span> 14<sup>th</sup> April 2018</li>
										<li class="blog-li4">Like</li>	
									</ul>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
									<a href="#" class="blog-btn">Read More</a>
								</div>
							</div>								
						</div>

						<div class="blog-sec1-mid">
							<div class="row">									
								<div class="blog-sec1-text">
									<h1>Article Name</h1>
									<ul>
										<li class="blog-li1"><span>By:</span> Author Name</li>
										<li class="blog-li3">Comment</li>
										<li class="blog-li2"><span>Posted on:</span> 14<sup>th</sup> April 2018</li>
										<li class="blog-li4">Like</li>	
									</ul>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
									<a href="#" class="blog-btn">Read More</a>
								</div>
							</div>								
						</div>	
					</div>

					<div id="menu1" class="tab-pane fade">
						<div class="blog-sec1-mid">
							<div class="row">									
								<div class="blog-sec1-text">
									<h1>Article Name</h1>
									<ul>
										<li class="blog-li1"><span>By:</span> Author Name</li>
										<li class="blog-li3">Comment</li>
										<li class="blog-li2"><span>Posted on:</span> 14<sup>th</sup> April 2018</li>
										<li class="blog-li4">Like</li>	
									</ul>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
									<a href="#" class="blog-btn">Read More</a>
								</div>
							</div>								
						</div>

						<div class="blog-sec1-mid">
							<div class="row">									
								<div class="blog-sec1-text">
									<h1>Article Name</h1>
									<ul>
										<li class="blog-li1"><span>By:</span> Author Name</li>
										<li class="blog-li3">Comment</li>
										<li class="blog-li2"><span>Posted on:</span> 14<sup>th</sup> April 2018</li>
										<li class="blog-li4">Like</li>	
									</ul>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
									<a href="#" class="blog-btn">Read More</a>
								</div>
							</div>								
						</div>

						<div class="blog-sec1-mid">
							<div class="row">									
								<div class="blog-sec1-text">
									<h1>Article Name</h1>
									<ul>
										<li class="blog-li1"><span>By:</span> Author Name</li>
										<li class="blog-li3">Comment</li>
										<li class="blog-li2"><span>Posted on:</span> 14<sup>th</sup> April 2018</li>
										<li class="blog-li4">Like</li>	
									</ul>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
									<a href="#" class="blog-btn">Read More</a>
								</div>
							</div>								
						</div>
					</div>

					<div id="menu2" class="tab-pane fade">
						<div class="blog-sec1-mid">
							<div class="row">									
								<div class="blog-sec1-text">
									<h1>Article Name</h1>
									<ul>
										<li class="blog-li1"><span>By:</span> Author Name</li>
										<li class="blog-li3">Comment</li>
										<li class="blog-li2"><span>Posted on:</span> 14<sup>th</sup> April 2018</li>
										<li class="blog-li4">Like</li>	
									</ul>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
									<a href="#" class="blog-btn">Read More</a>
								</div>
							</div>								
						</div>

						<div class="blog-sec1-mid">
							<div class="row">									
								<div class="blog-sec1-text">
									<h1>Article Name</h1>
									<ul>
										<li class="blog-li1"><span>By:</span> Author Name</li>
										<li class="blog-li3">Comment</li>
										<li class="blog-li2"><span>Posted on:</span> 14<sup>th</sup> April 2018</li>
										<li class="blog-li4">Like</li>	
									</ul>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
									<a href="#" class="blog-btn">Read More</a>
								</div>
							</div>								
						</div>

						<div class="blog-sec1-mid">
							<div class="row">									
								<div class="blog-sec1-text">
									<h1>Article Name</h1>
									<ul>
										<li class="blog-li1"><span>By:</span> Author Name</li>
										<li class="blog-li3">Comment</li>
										<li class="blog-li2"><span>Posted on:</span> 14<sup>th</sup> April 2018</li>
										<li class="blog-li4">Like</li>	
									</ul>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
									<a href="#" class="blog-btn">Read More</a>
								</div>
							</div>								
						</div>
					</div>								
				</div>	
			</div>
		</div>	

		<div class="row blog-pager">
			<ul class="pager">
				<li class="previous"><a href="#">Previous</a></li>
				<li class="next"><a href="#">Next</a></li>
			</ul>
		</div>

	</div>
</section>
<!-- /section1 -->
@endsection

laravel/resources/views/users/investor_forum.blade.php
@extends('users.layouts.master')
@push('header')
<script>
	function answer(id){
		$('#'+id).CRUD({
			url : '{{ route('forum-answer.store') }}'
		});
	}
</script>
@endpush
@section('content')

@php
function attrReplies($ans){
	$replies = $ans->replies();
	if($replies->count()){		
		$data = '';
		$data .= '<ul>';
		foreach ($replies->get() as $k => $v) {
			$rcount = $v->replies()->count();
			$data .= '<li>'
			.'<p>'.$v->fa_answer.'</p>'
			.'<span class="investor-reply">'
			.'<span>- '.$v->user->name.($v->user->type == 101 ? '(Admin)' : ''). ' </span>'	
			.'<a href="javascript:void(0)" onclick="reply('.$v->fa_id.');"><i class="fa fa-reply"></i> Reply '.($rcount ? '('.$rcount.')' : '').'</a>'
			.'</span>'
			.attrReplies($v)
			.'</li>';
		}
		$data .= '</ul>';

		return $data;
	}
}
@endphp
<section class="investor">
	<div class="container">
		<h1>Investor Forum <span class="investor-ask" data-toggle="modal" data-target="#investorModal">Ask Question</span></h1>
		<div class="row">
			<div class="panel-group" id="accordion">
				<div class = "jscroll">
					@forelse($investor_forums as $k => $if)
					<div class="panel panel-default">
						<div class="panel-heading">
							<a data-toggle="collapse" class="panel-title investor-title" data-parent="#accordion" href="#if{{ $if->if_id }}">
								<div>
									{{ $if->if_question }}
									<div>
										<ul>
											<li><span>Asked By:</span> {{ $if->if_anonymous ? 'Anonymous' : $if->user->name }}</li>
											<li><span>Posted on:</span> {{ $if->if_created_at->format('jS M, Y - h:i A') }}</li>
											<li>Comment <span class="badge">{{ $if->answers()->where(['fa_approve' => 1])->count() }}</span></li>
										</ul>
									</div>
								</div>
							</a>
						</div>
						<div id="if{{ $if->if_id }}" class="panel-collapse collapse">
							<div class="panel-body">
								<div class="investor-ans">
									<div class="row">

										@forelse ([1,0] as $ad)
										@forelse ($if->answers()->where(['fa_admin' => $ad, 'fa_approve' => 1])->get() as $aAns)
										@php
										$rCount = $aAns->replies()->count();
										@endphp
										<ul class="investor-ans-ul">
											<li>
												<p>{{ $aAns->fa_answer }}</p>
												<span class="investor-reply">
													<span>- {{ $aAns->user->name }} {{ $ad == 1 ? '(Admin)' : '' }}</span> 
													<a href="javascript:void(0)" onclick="reply('{{ $aAns->fa_id }}');"><i class="fa fa-reply"></i> Reply {{ $rCount ? '('.$rCount.')' : '' }}</a>
												</span>
												{!! attrReplies($aAns) !!}
											</li>
										</ul>
										<hr>
										@empty

										@endforelse
										@empty

										@endforelse
										@include('users.includes.answer_forms',['if' => $if])
									</div>
								</div>
							</div>
						</div>
					</div>	
					
					@empty
					@endforelse
					<div class="hidden">
						{!! $investor_forums->links() !!}
					</div>
				</div>
			</div> 
		</div>
	</div>
</section>

<div id="investorModal" class="modal fade" role="dialog">
	<div class="modal-dialog ananomis-modal">
		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close signup-close" data-dismiss="modal"><i class="fa fa-times"></i></button>
				<h4 class="modal-title">Ask Question Here</h4>
			</div>
			<div class="modal-body">
				<form id = "investorForm">
					<div class="form-group">
						<textarea class="form-control" cols="4" name = "question"></textarea>
					</div>
					<div class="checkbox">
						<label><input type="checkbox" name="anonymous"> Stay Anonymous</label>
					</div>
					<button type="submit" class="btn btn-default">Submit</button>
				</form>
			</div>
		</div>

	</div>
</div>

<div id="answerRModal" class="modal fade" role="dialog">
	<div class="modal-dialog ananomis-modal">
		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close signup-close" data-dismiss="modal"><i class="fa fa-times"></i></button>
				<h4 class="modal-title"></h4>
			</div>
			<div class="modal-body">
				<form id = "answerRForm">
					<input type="hidden" name="user" value="{{ Auth::id() }}">
					<input type="hidden" name="question" value="{{ $if->if_id }}">
					<input type="hidden" name="answer_on" id = "ansOn">
					<div class="form-group">
						<textarea class="form-control" placeholder="Your Comment" rows="3" name = "answer"></textarea>
					</div>
					<div class="form-group">
						<input type="submit" value="Add Comment" class="investor-btn">
					</div>
				</form>
			</div>
		</div>

	</div>
</div>
@endsection

@push('footer')
<script src="//unpkg.com/jscroll/dist/jquery.jscroll.min.js"></script>
<script>
	$(function() {
		$('.jscroll').jscroll({
			autoTrigger : true,
			nextSelector : '.pagination li.active + li a',
			contentSelector : 'div.jscroll',
			callback: function(){
				$('.pagination:visible:first').hide();
			},
			loadingHtml : '<div class = "loading-forum">Loading...</div>'
		});
	});
	$('#investorForm').CRUD({
		url : '{{ route('investor-forum.store') }}',
		processResponse : function (data){
			if(data.msg == 'success'){

			}
		},
		onLoad : 'check'
	});

	function reply(id){
		$('#answerRModal').modal('toggle');
		$('#ansOn').val(id);
	}

	$('#answerRForm').CRUD({
		url : '{{ route('forum-answer.store') }}'
	});
</script>
@endpush

laravel/resources/views/users/test1.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Facebook</title>
</head>
<body>

</body>
</html>