laravel/routes/web.php
<?php
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/browser', 'HomeController@browser')->name('browser');
Route::get('/fb', 'HomeController@fb')->name('fb');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/blogs', 'HomeController@blogs')->name('blogs');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/faqs', 'HomeController@faqs')->name('faqs');
Route::get('/services', 'HomeController@services')->name('services');
Route::get('/check-scrap', 'HomeController@checkScrap');
Route::get('/check-logout', 'HomeController@checkLogout');
Route::get('/check-date', 'HomeController@checkDate');
Route::get('/check-pdf-event', 'HomeController@checkPdfEvent');

Route::get('/past-performances', 'HomeController@pastPerformances')->name('past-performances');
Route::get('/services', 'HomeController@services')->name('services');
Route::get('/testimonials', 'HomeController@testimonials')->name('testimonials');
Route::get('/risk-profile', 'HomeController@riskProfile')->name('risk-profile');
Route::get('/terms', 'HomeController@terms')->name('terms');
Route::get('/privacy', 'HomeController@privacy')->name('privacy');
Route::get('login/facebook', 'HomeController@redirectToProvider');
Route::get('login/facebook/callback', 'HomeController@handleProviderCallback');
Route::get('ip', 'UserController@checkIpDetail');
Route::get('stock', 'UserController@checkStock');
Route::get('api-call', function(){
	return AlphaVantage\Api::stock()->daily('NSE:KEC');
});

Route::group(['middleware' => 'paid'], function() {
    Route::get('/current-recommendation', 'HomeController@currentRecommendation')->name('current-recommendation');
    Route::get('/investors-forum', 'HomeController@investorForum')->name('investor');
	Route::get('/reports/{id}/{name}', 'HomeController@stockReports')->name('stock-reports');
	Route::get('/view-report/{id}/{name}', 'StockReportController@viewReport')->name('view-report');
    Route::get('/download-report/{id}/{name}', 'StockReportController@downloadReport')->name('download-report');
});
Route::get('/admin/login', function() {
	return view('admin.login');
});

Route::resource('enquiry', 'EnquiryController');
Route::resource('investor-forum', 'InvestorForumController');
Route::get('pdf', 'UserController@pdf');
Route::get('watermark', 'UserController@watermark');

Route::get('client/{id}/kyc', 'KycController@upload')->name('kyc-upload');
Route::get('client/{id}/risk-profile/{edit?}', 'RiskProfileController@upload')->name('risk-upload');
Route::get('client/{id}/risk-profile-result', 'RiskProfileController@result')->name('risk-result');
Route::get('check', 'UserController@checkPDF');
Route::resource('forum-answer', 'ForumAnswerController');

Route::get('/pay','PaymentController@getPay')->name('get-pay');

Route::post('/paydemo','PaymentController@getPay')->name('pay');

Route::post('/placeorder','PaymentController@getPay')->name('placeorder');

Route::post('/paystatus','PaymentController@orderStatus')->name('orderStatus');

Route::resource('payment', 'PaymentController');

Route::get('/booked/order/{id}/{status?}', 'PaymentController@previous')->name('previous');

Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function(){	
	Route::get('/', function() {
		return view('admin.dashboard');
	})->name('home');
	
	Route::get('/check', function() {
		return view('admin.emails.normal');
	});

	Route::get('/download-kyc', 'UserController@downloadKyc')->name('download-kyc');
	Route::get('/download-stock', 'StockController@getStock')->name('download-stock');

	Route::resource('kyc', 'KycController');
	Route::resource('faq', 'FaqController');
	Route::resource('risk-profile', 'RiskProfileController');
	Route::resource('user', 'UserController');
	
	Route::get('clients/{type}/{tname}', 'UserController@getClients')->name('clients');
	
	Route::get('risk-profiles/{id}', 'RiskProfileController@allRiskProfile')->name('risk-profiles');
	Route::get('kycs/{id}/{type?}', 'KycController@allKycs')->name('kycs');
	Route::get('kycs-new', 'KycController@allKycsNew')->name('kycs-new');
	Route::get('all-user', 'UserController@allUser')->name('all-user');
	Route::get('all-stocks', 'StockController@allStocks')->name('all-stocks');	
	Route::get('all-logs', 'LoginLogController@allLogs')->name('all-logs');
	Route::get('all-logs-users', 'LoginLogController@allLogsUsers')->name('all-logs-users');
	Route::get('logs-users', 'LoginLogController@viewLogUser')->name('logs-users');	
	Route::get('all-forums', 'InvestorForumController@allForums')->name('all-forums');
	Route::get('logs/{id}', 'LoginLogController@logs')->name('logs');
	Route::post('payment-form', 'UserController@paymentForm')->name('payment-form');
	Route::post('block-form', 'LoginLogController@blockForm')->name('block-form');    
	Route::post('answer-form', 'InvestorForumController@answerForm')->name('answer-form');
	Route::post('approve-form', 'StockController@approveForm')->name('approve-form');	
	Route::post('all-answers', 'ForumAnswerController@allAnswers')->name('all-answers');

	Route::resource('investor-forum', 'InvestorForumController');
	Route::resource('current-recommendation', 'CurrentRecommendationController');
	Route::resource('stock', 'StockController');
	Route::resource('login-log', 'LoginLogController');
	Route::resource('stock-report', 'StockReportController');
	Route::resource('forum-answer', 'ForumAnswerController');
});

laravel/resources/views/admin/layouts/footer.blade.php
        <!-- footer content -->
        <footer>
          <div class="pull-right">
            {{ config('app.name') }}
        </div>
        <div class="clearfix"></div>
    </footer>
    <!-- /footer content -->
</div>
</div>

<!-- jQuery -->
<script src="{{ asset('admin-assets/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap -->
<script src="{{ asset('admin-assets/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('admin-assets/fastclick/lib/fastclick.js') }}"></script>
<!-- NProgress -->
<script src="{{ asset('admin-assets/nprogress/nprogress.js') }}"></script>
<script src="{{ asset('admin-assets/js/custom.js') }}"></script>
<script src="{{ asset('js/crud.js') }}"></script>
<script type="text/javascript">
	var mainUrl = '{{ route('home') }}/';
	$(window).on('load',function(){
		$('#loader').addClass('hidden');
	});
</script>
@stack('footer')
</body>
</html>

laravel/resources/views/admin/layouts/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>{{ config('app.name') }} (Admin) | @yield('title')</title>
  <link rel="icon" href="{{ asset('img/fav.png') }}" type="image/x-icon" />

  <!-- Bootstrap -->
  <link href="{{ asset('admin-assets/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
  <!-- Font Awesome -->
  <link href="{{ asset('admin-assets/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
  <!-- NProgress -->
  <link href="{{ asset('admin-assets/nprogress/nprogress.css') }}" rel="stylesheet">
  <!-- bootstrap-daterangepicker -->
  

  <!-- Custom Theme Style -->
  <link href="{{ asset('admin-assets/css/custom.css') }}" rel="stylesheet">
  <style type="text/css">
  #loader{
    height: 100%;
    width: 100%;
    text-align: center;
    padding-top: 22%;
    position: fixed;
    background: #2A3F54;
    z-index: 9999;
  }
</style>
@stack('header')
</head>

<body class="nav-md">
  <div id = "loader">
    <h1>Loading...</h1>
  </div>  
  <div class="container body">
    <div class="main_container">
      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="{{ route('admin.home') }}" class="site_title"> <span>{{ config('app.name') }}</span></a>
          </div>

          <div class="clearfix"></div>

          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <div class="profile_pic">
              <img src="{{ asset('img/logo.png') }}" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>Welcome,</span>
              <h2>{{ Auth::user()->name }}</h2>
            </div>
          </div>
          <!-- /menu profile quick info -->

          <br />

          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              {{-- <h3>General</h3> --}}
              <ul class="nav side-menu">                
                @if (Auth::user()->type == 101)
                <li><a href="{{ route('admin.clients', ['type' => 0, 'tname' => 'new']) }}"><i class="fa fa-home"></i> New Subscriber</a></li>
                <li><a href="{{ route('admin.clients', ['type' => 1, 'tname' => 'paid']) }}"><i class="fa fa-home"></i> Paid Clients</a></li>
                <li><a href="{{ route('admin.investor-forum.index') }}"><i class="fa fa-home"></i> Investoer Forum</a></li>
                <li><a href="{{ route('admin.current-recommendation.create') }}"><i class="fa fa-home"></i> Current Recommendation</a></li>
                <li><a href="{{ route('admin.stock-report.create') }}"><i class="fa fa-home"></i> Upload Report</a></li>
                <li><a href="{{ route('admin.logs-users') }}"><i class="fa fa-home"></i> Login Logs</a></li>
                  <li><a href="{{ route('admin.stock.index') }}"><i class="fa fa-home"></i> Stocks</a></li>
                <li><a><i class="fa fa-home"></i>Faqs<span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="{{ route('admin.faq.index') }}">All Faqs</a></li>
                    <li><a href="{{ route('admin.faq.create') }}">Create Faq</a></li>
                  </ul>
                </li>                
               {{--  <li><a href="{{ route('admin.clients') }}"><i class="fa fa-home"></i> Clients </a></li>
                <li><a><i class="fa fa-home"></i>Articles <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="{{ route('admin.article.create') }}">Create Article</a></li>
                    <li><a href="{{ route('admin.article.index') }}">View Articles</a></li>
                  </ul>
                </li>             
                <li><a><i class="fa fa-home"></i>Investor Education <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="{{ route('admin.investor-education.create') }}">Create Investor Education</a></li>
                    <li><a href="{{ route('admin.investor-education.index') }}">View Investor Educations</a></li>
                  </ul>
                </li>                
                <li><a href="{{ route('admin.enquiry.index') }}"><i class="fa fa-home"></i> Investor Education Enquiries </a></li> --}}
                
                @else
                {{-- <li><a href="{{ route('kyc-upload', ['id' => Auth::id()]) }}"><i class="fa fa-home"></i> Weekly Report </a></li> --}}
                @endif
              </ul>
            </div>
            

          </div>
          <!-- /sidebar menu -->

          <!-- /menu footer buttons -->
          <div class="sidebar-footer hidden-small hidden">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
              <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
              <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
          </div>
          <!-- /menu footer buttons -->
        </div>
      </div>

      <!-- top navigation -->
      <div class="top_nav">
        <div class="nav_menu">
          <nav>
            <div class="nav toggle">
              <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">Log Out <i class="fa fa-sign-out"></i> 
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  {{ csrf_field() }}
                </form>                
              </li>                      
            </ul>
          </nav>
        </div>
      </div>
        <!-- /top navigation -->

laravel/resources/views/admin/layouts/master.blade.php
@include('admin.layouts.header')
@yield('content')
@include('admin.layouts.footer')