laravel/routes/web.php
<?php
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/browser', 'HomeController@browser')->name('browser');
Route::get('/fb', 'HomeController@fb')->name('fb');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/blogs', 'HomeController@blogs')->name('blogs');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/faqs', 'HomeController@faqs')->name('faqs');
Route::get('/services', 'HomeController@services')->name('services');
Route::get('/check-scrap', 'HomeController@checkScrap');
Route::get('/check-logout', 'HomeController@checkLogout');
Route::get('/check-date', 'HomeController@checkDate');
Route::get('/check-pdf-event', 'HomeController@checkPdfEvent');

Route::get('/past-performances', 'HomeController@pastPerformances')->name('past-performances');
Route::get('/services', 'HomeController@services')->name('services');
Route::get('/testimonials', 'HomeController@testimonials')->name('testimonials');
Route::get('/risk-profile', 'HomeController@riskProfile')->name('risk-profile');
Route::get('/terms', 'HomeController@terms')->name('terms');
Route::get('/privacy', 'HomeController@privacy')->name('privacy');
Route::get('login/facebook', 'HomeController@redirectToProvider');
Route::get('login/facebook/callback', 'HomeController@handleProviderCallback');
Route::get('ip', 'UserController@checkIpDetail');
Route::get('stock', 'UserController@checkStock');
Route::get('api-call', function(){
	return AlphaVantage\Api::stock()->daily('NSE:KEC');
});

Route::group(['middleware' => 'paid'], function() {
    Route::get('/current-recommendation', 'HomeController@currentRecommendation')->name('current-recommendation');
    Route::get('/investors-forum', 'HomeController@investorForum')->name('investor');
	Route::get('/reports/{id}/{name}', 'HomeController@stockReports')->name('stock-reports');
	Route::get('/view-report/{id}/{name}', 'StockReportController@viewReport')->name('view-report');
    Route::get('/download-report/{id}/{name}', 'StockReportController@downloadReport')->name('download-report');
});
Route::get('/admin/login', function() {
	return view('admin.login');
});

Route::resource('enquiry', 'EnquiryController');
Route::resource('investor-forum', 'InvestorForumController');
Route::get('pdf', 'UserController@pdf');
Route::get('watermark', 'UserController@watermark');

Route::get('client/{id}/kyc', 'KycController@upload')->name('kyc-upload');
Route::get('client/{id}/risk-profile/{edit?}', 'RiskProfileController@upload')->name('risk-upload');
Route::get('client/{id}/risk-profile-result', 'RiskProfileController@result')->name('risk-result');
Route::get('check', 'UserController@checkPDF');
Route::resource('forum-answer', 'ForumAnswerController');

Route::get('/pay','PaymentController@getPay')->name('get-pay');

Route::post('/paydemo','PaymentController@getPay')->name('pay');

Route::post('/placeorder','PaymentController@getPay')->name('placeorder');

Route::post('/paystatus','PaymentController@orderStatus')->name('orderStatus');

Route::resource('payment', 'PaymentController');

Route::get('/booked/order/{id}/{status?}', 'PaymentController@previous')->name('previous');

Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function(){	
	Route::get('/', function() {
		return view('admin.dashboard');
	})->name('home');
	
	Route::get('/check', function() {
		return view('admin.emails.normal');
	});

	Route::get('/download-kyc', 'UserController@downloadKyc')->name('download-kyc');
	Route::get('/download-stock', 'StockController@getStock')->name('download-stock');

	Route::resource('kyc', 'KycController');
	Route::resource('faq', 'FaqController');
	Route::resource('risk-profile', 'RiskProfileController');
	Route::resource('user', 'UserController');
	
	Route::get('clients/{type}/{tname}', 'UserController@getClients')->name('clients');
	
	Route::get('risk-profiles/{id}', 'RiskProfileController@allRiskProfile')->name('risk-profiles');
	Route::get('kycs/{id}/{type?}', 'KycController@allKycs')->name('kycs');
	Route::get('kycs-new', 'KycController@allKycsNew')->name('kycs-new');
	Route::get('all-user', 'UserController@allUser')->name('all-user');
	Route::get('all-stocks', 'StockController@allStocks')->name('all-stocks');	
	Route::get('all-logs', 'LoginLogController@allLogs')->name('all-logs');
	Route::get('all-logs-users', 'LoginLogController@allLogsUsers')->name('all-logs-users');
	Route::get('logs-users', 'LoginLogController@viewLogUser')->name('logs-users');	
	Route::get('all-forums', 'InvestorForumController@allForums')->name('all-forums');
	Route::get('logs/{id}', 'LoginLogController@logs')->name('logs');
	Route::post('payment-form', 'UserController@paymentForm')->name('payment-form');
	Route::post('block-form', 'LoginLogController@blockForm')->name('block-form');    
	Route::post('answer-form', 'InvestorForumController@answerForm')->name('answer-form');
	Route::post('approve-form', 'StockController@approveForm')->name('approve-form');	
	Route::post('all-answers', 'ForumAnswerController@allAnswers')->name('all-answers');

	Route::resource('investor-forum', 'InvestorForumController');
	Route::resource('current-recommendation', 'CurrentRecommendationController');
	Route::resource('stock', 'StockController');
	Route::resource('login-log', 'LoginLogController');
	Route::resource('stock-report', 'StockReportController');
	Route::resource('forum-answer', 'ForumAnswerController');
});

laravel/resources/views/admin/create_current_recommendation.blade.php
@extends('admin.layouts.master')
@section('title')
Create New Recommendation
@endsection

@php
	$ID = 'current-recommendation';
@endphp
@push('header')
	<link href="{{ asset('css/bootstrap-datetimepicker.min.css') }}" rel="stylesheet" media="screen">
@endpush
@section('content')
<div class="right_col" role="main">	
	<div class="page-title">
		<div class="title_left">
			<h3>Create New Recommendation</h3>
		</div>
		<div class="pull-right">
			<a href = "{{ route('admin.'.$ID.'.index') }}" class="btn btn-danger">Back</a>
		</div>
	</div>
	<div class="clearfix">
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">				
				<div class="x_content">
					@include('admin.forms.current_recommendation_form', ['ID' => $ID])
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

@push('footer')
	<script type="text/javascript" src = "{{ asset('js/bootstrap-datetimepicker.js') }}"></script>
	<script type="text/javascript">
		$('#datetimepicker1').datetimepicker({
			todayHighlight:'TRUE',
			autoclose: true,
			minDate: '0',
			maxDate: '+1Y+6M'
		});
	</script>
@endpush

laravel/resources/views/admin/create_investor_education.blade.php
@extends('admin.layouts.master')
@section('title')
Create Investor Education
@endsection
@php
	$ID = 'investor-education';
@endphp
@section('content')
<div class="right_col" role="main">	
	<div class="page-title">
		<div class="title_left">
			<h3>Create Investor Education</h3>
		</div>
		<div class="pull-right">
			<a href = "{{ route('admin.'.$ID.'.index') }}" class="btn btn-danger">Back</a>
		</div>
	</div>
	<div class="clearfix">
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">				
				<div class="x_content">
					@include('admin.forms.investor_education_form')
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

laravel/resources/views/admin/create_stock_report.blade.php
@extends('admin.layouts.master')
@section('title')
Create Stock Report
@endsection

@php
	$ID = 'stock-report';
@endphp
@section('content')
<div class="right_col" role="main">	
	<div class="page-title">
		<div class="title_left">
			<h3>Create Stock Report</h3>
		</div>
		<div class="pull-right">
			<a href = "{{ route('admin.'.$ID.'.index') }}" class="btn btn-danger">Back</a>
		</div>
	</div>
	<div class="clearfix">
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">				
				<div class="x_content">
					@include('admin.forms.stock_report_form', ['ID' => $ID])
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

laravel/resources/views/admin/edit_faq.blade.php
@extends('admin.layouts.master')
@section('title')
Edit FAQ
@endsection

@php
	$ID = 'faq';
@endphp
@section('content')
<div class="right_col" role="main">	
	<div class="page-title">
		<div class="title_left">
			<h3>Edit FAQ</h3>
		</div>
		<div class="pull-right">
			<a href = "{{ route('admin.'.$ID.'.index') }}" class="btn btn-danger">Back</a>
		</div>
	</div>
	<div class="clearfix">
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">				
				<div class="x_content">
					@include('admin.forms.faq_form', ['ID' => $ID, 'faq' => $faq])
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

laravel/resources/views/admin/edit_investor_education.blade.php
@extends('admin.layouts.master')
@section('title')
Edit Investor Education
@endsection
@php
	$ID = 'investor-education';
@endphp
@section('content')
<div class="right_col" role="main">	
	<div class="page-title">
		<div class="title_left">
			<h3>Edit Investor Education</h3>
		</div>
		<div class="pull-right">
			<a href = "{{ route('admin.'.$ID.'.index') }}" class="btn btn-danger">Back</a>
		</div>
	</div>
	<div class="clearfix">
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">				
				<div class="x_content">
					@include('admin.forms.investor_education_form',['investorEducation' => $investorEducation])
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

laravel/resources/views/admin/edit_monthly_performance.blade.php
@extends('admin.layouts.master')
@section('title')
Edit Monthly Performance
@endsection
@php
	$ID = 'monthly-performance';
@endphp
@section('content')
<div class="right_col" role="main">	
	<div class="page-title">
		<div class="title_left">
			<h3> Edit Monthly Performance</h3>
		</div>
		<div class="pull-right">
			<a href = "{{ route('admin.'.$ID.'.index') }}" class="btn btn-danger">Back</a>
		</div>
	</div>
	<div class="clearfix">
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">				
				<div class="x_content">
					@include('admin.forms.monthly_performance_form', ['mp' => $mp])
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

laravel/resources/views/admin/edit_stock.blade.php
@extends('admin.layouts.master')
@section('title')
Edit Stock
@endsection

@php
	$ID = 'stock';
@endphp

@section('content')
<div class="right_col" role="main">	
	<div class="page-title">
		<div class="title_left">
			<h3>Edit</h3>
		</div>
		<div class="pull-right">
			<a href = "{{ route('admin.'.$ID.'.index') }}" class="btn btn-danger">Back</a>
		</div>
	</div>
	<div class="clearfix">
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">				
				<div class="x_content">
					@include('admin.forms.stock_form', ['ID' => $ID, 'stock' => $stock])
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

laravel/resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" type="image/x-icon" href="{{ asset('images/fav.png') }}"> 

  <title>{{ config('app.name') }} (Admin)</title>

  <!-- Bootstrap -->
  <link href="{{ asset('admin-assets/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
  <!-- Font Awesome -->
  <link href="{{ asset('admin-assets/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
  <!-- NProgress -->
  <link href="{{ asset('admin-assets/nprogress/nprogress.css') }}" rel="stylesheet">
  <!-- Animate.css -->
  <link href="{{ asset('admin-assets/animate.css/animate.min.css') }}" rel="stylesheet">

  <!-- Custom Theme Style -->
  <link href="{{ asset('admin-assets/css/custom.min.css') }}" rel="stylesheet">
</head>

<body class="login">
  <div>
    <a class="hiddenanchor" id="signup"></a>
    <a class="hiddenanchor" id="signin"></a>

    <div class="login_wrapper">
      <div class="animate form login_form">
        <section class="login_content">
          <form class="form-horizontal" method="POST" action="{{ route('login') }}">
            {{ csrf_field() }}
            <h1>Admin Login</h1>
            <div>
              <input placeholder="Email" id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required autofocus>

              @if ($errors->has('email'))
              <span class="help-block">
                <strong>{{ $errors->first('email') }}</strong>
              </span>
              @endif              
            </div>
            <div>
              <input placeholder="Password" id="password" type="password" class="form-control" name="password" required>

              @if ($errors->has('password'))
              <span class="help-block">
                <strong>{{ $errors->first('password') }}</strong>
              </span>
              @endif              
            </div>
            <div>
              <button class="btn btn-default submit">Log in</button>
              <a class="reset_pass" href="#">Lost your password?</a>
            </div>

            <div class="clearfix"></div>

            <div class="separator">
              {{-- <p class="change_link">New to site?
                <a href="#signup" class="to_register"> Create Account </a>
              </p> --}}

              <div class="clearfix"></div>
              <br />

              {{-- <div class="text-center">
                <img src="{{ asset('images/logo-black.png') }}" width="100%">
              </div> --}}
            </div>
          </form>
        </section>
      </div>
    </div>
  </div>
</body>
</html>

laravel/resources/views/admin/view_investor_forum.blade.php
@extends('admin.layouts.master')

@section('title')
    All Forum Questions
@endsection

@push('header')
    <!-- Datatables -->


    {{-- <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css"> --}}

    <link href="{{ asset('admin-assets/datatables.net-bs/css/dataTables.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('admin-assets/datatables.net-buttons-bs/css/buttons.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('admin-assets/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('admin-assets/datatables.net-responsive-bs/css/responsive.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('admin-assets/datatables.net-scroller-bs/css/scroller.bootstrap.min.css') }}" rel="stylesheet">
    @php
        $ID = 'forum';
    @endphp
@endpush

@section('content')

    <!-- page content -->
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>All Forum Questions</h3>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_content">
                            <table id="forum-table" class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th>Question</th>
                                    <th>User</th>
                                    <th>Date</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal fade" id="{{ $ID }}ViewModal" tabindex="-1" role="dialog" aria-labelledby="Modal" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="{{ $ID }}ModalLabel">View {{ $ID }}</h4>
                        </div>
                        <div class="modal-body" id = "viewData">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('footer')


    <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>



    <script src="{{ asset('admin-assets/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>

    <script src="{{ asset('admin-assets/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script>
    <script src="{{ asset('admin-assets/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
    <script src="{{ asset('admin-assets/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('admin-assets/datatables.net-responsive-bs/js/responsive.bootstrap.js') }}"></script>
    <script src="{{ asset('admin-assets/datatables.net-scroller/js/dataTables.scroller.min.js') }}"></script>

    <script src="{{ asset('admin-assets/jszip/dist/jszip.min.js') }}"></script>

    <script src="{{ asset('admin-assets/pdfmake/build/pdfmake.min.js') }}"></script>
    <script src="{{ asset('admin-assets/pdfmake/build/vfs_fonts.js') }}"></script>

    <script type="text/javascript">

        {{-- Table.init(ID); --}}

        function viewDetail(id, url) {
            $('#{{ $ID }}ViewModal').modal('toggle');
            $('#viewData').html('<div class="text-center">Loading...</div>');
            $.post(url, {id : id}, function( data ) {
                $('#viewData').html(data);
            });
        }

        $(function() {
            $('#forum-table').DataTable({
                processing: true,
                serverSide: true,
                pageLength : 50,
                ajax: {
                    url : '{!! route('admin.all-forums') !!}'
                },
                columns: [
                    { data: 'if_question', name: 'if_question' },
                    { data: 'name', name: 'name' },
                    { data: 'if_created_at', name: 'if_created_at', "orderable": false },
                    { data: 'action', name: 'action',"orderable": false }
                ],
                dom: "Bfrtip",
                buttons: [
                    {
                        extend: "excel",
                        className: "btn-sm",
                        exportOptions: {
                            columns: [0,1,2]
                        }
                    },
                    {
                        extend: "pdfHtml5",
                        className: "btn-sm",
                        exportOptions: {
                            columns: [0,1,2]
                        }
                    }
                ],
                responsive: true,
            });
        });
        function addAnswer(){
            $('#answerForm').CRUD({
                url : '{{ route('admin.forum-answer.store') }}'
            });
        }
    </script>
@endpush

laravel/resources/views/admin/view_risk_profiles.blade.php
@extends('admin.layouts.master')

@section('title')
All Risk profile of {{ $user->name }}
@endsection
@push('header')
<!-- Datatables -->
<link href="{{ asset('admin-assets/datatables.net-bs/css/dataTables.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-buttons-bs/css/buttons.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-responsive-bs/css/responsive.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-scroller-bs/css/scroller.bootstrap.min.css') }}" rel="stylesheet">
@php
$ID = 'risk-profile';
@endphp
@endpush

@section('content')

<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>All Risk profile of {{ $user->name.' ('.$user->mobile.')' }}</h3>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">            
            <table id="users-table" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Created at</th>
                  <th>Score</th>                  
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                @forelse ($riskProfiles as $k => $rp)
                <tr id = "tr-{{ $rp->rp_id }}">            
                  <td>{{ ++$k }}</td>                  
                  <td>{{ \Carbon\Carbon::parse($rp->rp_created_at)->format('jS M, Y') }}</td>
                  <td>{{ $rp->rp_score }}</td>        
                  <td>
                    <button  class="btn btn-primary btn-xs" onclick="viewDetail('{{ $rp->rp_id }}');"><i class="fa fa-eye"></i> View</button>
                  </td>                                                
                </tr>
                @empty                    
                @endforelse
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="{{ $ID }}ViewModal" tabindex="-1" role="dialog" aria-labelledby="Modal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="{{ $ID }}ModalLabel">View {{ $ID }}</h4>
          </div>
          <div class="modal-body" id = "viewData"></div>
        </div>
      </div>
    </div>

    {{-- <div class="modal fade" id="{{ $ID }}DModal" tabindex="-1" role="dialog" aria-labelledby="Modal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header text-center">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Are You Sure you want to delete <span id = "delName"></span> category ? it'll also delete all related Sub Categories, Child Categories and Products</h4>
            <br>
            <div>
              <form id = "{{ $ID }}DForm">
                <button type = "button" class="btn btn-danger" id = "yes">Yes</button>
                <button type = "button" class="btn btn-success" data-dismiss="modal">No</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div> --}}
  </div>
</div>

@endsection

@push('footer')
<script src="{{ asset('admin-assets/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
{{-- <script src="{{ asset('admin-assets/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script> --}}
<script src="{{ asset('admin-assets/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-responsive-bs/js/responsive.bootstrap.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-scroller/js/dataTables.scroller.min.js') }}"></script>
<script src="{{ asset('admin-assets/jszip/dist/jszip.min.js') }}"></script>
<script src="{{ asset('admin-assets/pdfmake/build/pdfmake.min.js') }}"></script>
<script src="{{ asset('admin-assets/pdfmake/build/vfs_fonts.js') }}"></script>

<script type="text/javascript">  

  Table.init(ID);
  function viewDetail(id) {
    $('#viewData').html('<div class="text-center">Loading...</div>');
    $('#{{ $ID }}ViewModal').modal('toggle');
    $.ajax({
      url : '{{ route('admin.risk-profile.index') }}/'+id,
      type : 'get',
      success : function(data){
        $('#viewData').html(data);
        console.log(data);
      }
    });
  }
</script>
@endpush